### PR TITLE
Calculator layout using components

### PR DESCRIPTION
**Pull request by Jord4N-AC**
In this part of my [project](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/sneak_peek.md), I developed the UI and layout, I did it using React components, I did not add the math logic to make it work, that will be added later.

### [Project requirements](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/project_components.md)

- Delete the boilerplate from `create-react-app` (text, images, styles)
- Create a directory called `components`
- Inside `components`, create `Calculator.js` file
- In `Calculator.js`, create a React component that matches [the design](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/images/calculator.png)
- Use JSX, and CSS to implement [the design](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/images/calculator.png)
- Use functional components
- Create at least 1 child component
- Use the `Calculator` component in the top-level (`App.js`)
- Make sure the App works properly (Open it in the browser)

### General requirements

- Follow [JavaScript best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md)
- Use correct [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md)
- Document my work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
- Check [linter errors](https://github.com/microverseinc/linters-config)
- Open Pull request and ask for [review](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/how_to_ask_for_a_code_review.md)

### CODE REVIEW

**Review by rloterh — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi Shayan,  

Your project is complete! 🏁 There is nothing else to say other than... it's time to merge it 🍾
Congratulations!  🎉 💯 🌟 

## Highlights 🎯 
🎲 Calculator components correctly added!
🎲 Calculator layout matches given template!
🎲 Professional ReadMe!

Cheers..Happy coding! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Jord4N-AC** [comment]
@rloterh thank you so much

**Review by ridwanediallo — COMMENTED** [review]
# STATUS: APPROVED 🟢
## Hi @Jord4N-AC , 
Congratulations!GIF

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- You PR has a good title and a desctitive summary. ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Reem-lab** [comment]
# Hi @Jord4N-AC,  👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights
- [ ] Great job on the funtionality for component💯

- [ ] Followed Gitflow 🔥
- [ ] No Linters error ✅
- [ ] Kudos on the design⭐

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
